export const debugMode = false
const HOUR = 60 * 60 * 1000
export const ONE_DAY_MS = 24 * HOUR
export const SEVEN_DAYS_MS = 7 * ONE_DAY_MS
export const allowCachingFallback: boolean = false
export const CACHE_HISTORY_BLOB_KEY = 'cache_history'
export const CACHE_BLOB_KEY = 'cache_coins'
export const SOURCE_CRYPTORATES = 'cryptorates'
export const SOURCE_COINCAP = 'coincap'
export const NETLIFY_DEV = true
